name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      env: 
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Pack with dotnet
      run: dotnet pack --configuration Release -o $(pwd)/packages
    - name: Push to nuget
      run: nuget push packages/*.nupkg --skip-duplicate --no-symbols true
